application: sendmeform
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: tpl/js
  
- url: /css
  static_dir: tpl/css
  
- url: /img
  static_dir: tpl/img

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
